### ISSUE TITLE
Broken link: https://docs.quix.io/sdk/features/data-frames.html

### ISSUE THREAD

**Issue by castagna** [quixai/quix-docs#105]
Page is: https://docs.quix.io/sdk/features/data-frames.html
Click on TimeseriesData (https://docs.quix.io/sdk/consume.md#timeseriesdata-format) --> 404

**Comment by tbedford** [comment]
I think this has been fixed. `consume.md` should have been `subscribe.md`. Several instances were fixed by:

https://github.com/quixio/quix-streams/pull/66

However, the fix is not yet in the live docs. Also, `/sdk/` will change to `/client-library/`.

**Comment by SteveRosam** [comment]
We have also added a redirection plugin to the docs. The release is being prepared now.

**Comment by tbedford** [comment]
The fix is now in the production / live docs.
