### ISSUE TITLE
Document the stream replay functionality in Quix platform

### ISSUE THREAD

**Issue by merlin-quix** [quixai/quix-docs#114]
A nice man called Peter Nagy helped me find the stream replay functionality in the Quix platform, but it is not documented at all. Can you add some documentation for it?
![image](https://user-images.githubusercontent.com/116729413/227327981-c2e7ed14-1d26-4ad1-9f40-cb9b95dade5b.png)

For reference, here's the original conversation in 'The Stream": 
https://stream-processing.slack.com/archives/C033BGFD1L6/p1679595803505779

**Comment by tbedford** [comment]
There's now a howto [here](https://github.com/quixio/quix-docs/blob/dev/docs/platform/how-to/replay.md).

@merlin-quix - anything else you need to know about replay that I can add into the docs?
