### ISSUE TITLE
404ing link in InfluxDB section

### ISSUE THREAD

**Issue by jackquix** [quixai/quix-docs#335]
On this page: 

https://github.com/quixio/quix-docs/blob/58387f7fc53ce5e6ebf5629e6a0be999ee507cd2/docs/integrations/databases/influxdb/alerting.md#L4

The connector link for Twilio 404s.

**Comment by tbedford** [comment]
Fixed with [this commit](https://github.com/quixio/quix-docs/commit/345ff3156375c9fd42027b01afe806c850959ee8).
