### ISSUE TITLE
Sentiment Analysis tutorial issues

### ISSUE THREAD

**Issue by PatrickMiraP** [quixai/quix-docs#34]
Tested on this PR https://github.com/quixai/quix-docs/pull/30

- code in tutorial has an undefined variable
![image](https://user-images.githubusercontent.com/725598/207405244-8783936f-9cc5-499d-8bd8-117190c524e6.png)
It works after renaming df_all_messages to df
- In Tweet transformation part, remove extra backslashes 
![image](https://user-images.githubusercontent.com/725598/207405426-62655509-7589-4c0f-a043-f9f6b46a448e.png)

**Comment by tbedford** [comment]
All the issues raised here were fixed when the [tutorial was revamped](https://docs.quix.io/platform/tutorials/sentiment-analysis/index.html) a while back. (I checked against the currently published docs).

Closing as resolved. 
FYI: @SteveRosam
