### ISSUE TITLE
Quick start tutorial findings

### ISSUE THREAD

**Issue by luisquix** [quixai/quix-docs#37]
No link to the platform
Typo: Get up and running **In** this section

-  "3. Click Edit code not the same"
![different text](https://user-images.githubusercontent.com/120378585/207407138-0c088313-77d2-4a37-8f99-0dac8bcdefd8.png)

- Ensure that the input is set to messages and the output is set to sentiment
	- Did I miss a step? "Messages" is not a part of the dropdown
	- What does "Messages" mean when you add type it by hand?
	
- Locate the line of code that creates the output stream
	Code to copy and paste is missing spaces around '=', so copy pasting is not usefull
	
- "8. Click Deploy near the top right corner"
	- It didn't mention a popup because I didn't save? should I have saved?
		- Difference between "Do not commit" and "Cancel"
		- "Save and commit" is not related to the action I wanted to do.
		
![Captura de pantalla (9)](https://user-images.githubusercontent.com/120378585/207407678-bbd3e9a7-298c-4cc4-bf3a-e6f3de7f5853.png)

- Change the memory in deployment settings to at least 4GB
	Maximum is 1GB
	
![Captura de pantalla (10)](https://user-images.githubusercontent.com/120378585/207407875-c3c5d384-22ae-4626-9876-e679827abd2f.png)

	
- Demo UI
        -  "3. Click Edit code not the same"
![different text](https://user-images.githubusercontent.com/120378585/207407138-0c088313-77d2-4a37-8f99-0dac8bcdefd8.png)
	- 4. Now I see "Edit code", do I click it again?

**Comment by tbedford** [comment]
This was very useful feedback. Thank you!

However, the Quickstart was [revamped](https://docs.quix.io/platform/tutorials/quick-start/quick-start.html) back in January I think, and I believe most of these issues have now been resolved.

We do also now prompt the developer to save, before clicking deploy, so the "unsaved changes" dialog should not appear. However, the issue of the "unsaved changes" dialog is an interesting one - what is the difference between "Do not commit" and "Cancel"? I believe the difference would be that cancel cancels the dialog completely, and so takes you back to the **unsaved state**, whereas "Do not commit" would save the text but not make a commit, but the next commit would include the saved changes. I will verify, add a note (a tip would be useful) just in case that dialog does arise. I will report back here when the work is done.

**Comment by tbedford** [comment]
Having taken a look, there was probably some feedback as the dialog has changed:

![image](https://user-images.githubusercontent.com/25511700/227237756-f960c08e-6233-4552-8f19-f7cdf319dc61.png)

You either commit your changes, or lose them. That seems pretty straightforward, and no need to add a tip now. The close button and discard changes button basically do the same thing.
